---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: lint
  pull: always
  image: quay.io/coreos/jsonnet-ci:latest
  commands:
  - apt-get update && apt-get install xz-utils
  # This step requires golancilint, promtool and jsonnetfmt
  - make lint
  - git diff --exit-code

- name: test
  pull: always
  image: golang:1.13
  commands:
  - make test

- name: build
  pull: always
  image: golang:1.13
  commands:
  - make build
