global:
  scrape_interval:     1s # Super short interval for demo purposes. Avoid this on production setups!

scrape_configs:
  - job_name: 'demo'
    static_configs:
      - targets: ['localhost:8080']